"""
Learning Academy — Phase 6.

Course/lesson STRUCTURE is curated (academy_curriculum.py); lesson CONTENT
and quizzes are generated by Claude the first time anyone opens a lesson,
then cached on the Lesson row and reused for every user after that — one
generation per lesson ever, not one per user.

Lessons and quizzes are free for everyone (matches the roadmap's own free
tier, which includes basic lessons/quizzes). Certificates — the tangible
credential for finishing a whole course — are a Premium perk, the same
freemium pattern as course platforms that let you audit free and pay for
the certificate.
"""
import json
import re
import secrets
from datetime import datetime

from anthropic import Anthropic, APIError

from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, InputFile
from telegram.ext import ContextTypes

from database import SessionLocal
from models import User, Course, Lesson, LessonProgress, Certificate
from handlers.subscription import require_premium
from handlers.safe_text import md
from media.certificate import generate_certificate_png
import config
import keyboards

_client = Anthropic(api_key=config.ANTHROPIC_API_KEY) if config.ANTHROPIC_API_KEY else None


# ---------- Home / course / lesson browsing ----------

async def show_academy_home(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    tg_user = update.effective_user

    session = SessionLocal()
    try:
        user = session.query(User).filter_by(telegram_id=tg_user.id).first()
        if not user or not user.registration_complete:
            text = "Send /start first to set up your profile."
            if query:
                await query.answer()
                await query.edit_message_text(text)
            else:
                await update.message.reply_text(text)
            return

        courses = session.query(Course).order_by(Course.order_index).all()
        rows = []
        for c in courses:
            total = len(c.lessons)
            done = (
                session.query(LessonProgress)
                .join(Lesson, LessonProgress.lesson_id == Lesson.id)
                .filter(LessonProgress.user_id == user.id, Lesson.course_id == c.id)
                .count()
            )
            rows.append([InlineKeyboardButton(f"{c.title} ({done}/{total})", callback_data=f"acad:course:{c.id}")])
        rows.append([InlineKeyboardButton("🎓 My Certificates", callback_data="acad:certs")])
        rows.append([InlineKeyboardButton("⬅️ Back to Menu", callback_data="menu:main")])

        text = "📚 *Learning Academy*\n\nCourses on coaching, nutrition, psychology, the laws of the game, and more."
        markup = InlineKeyboardMarkup(rows)
        if query:
            await query.answer()
            await query.edit_message_text(text, parse_mode="Markdown", reply_markup=markup)
        else:
            await update.message.reply_text(text, parse_mode="Markdown", reply_markup=markup)
    finally:
        session.close()


async def show_course(update: Update, context: ContextTypes.DEFAULT_TYPE, course_id: int):
    query = update.callback_query
    await query.answer()
    tg_user = update.effective_user

    session = SessionLocal()
    try:
        user = session.query(User).filter_by(telegram_id=tg_user.id).first()
        if not user:
            await query.edit_message_text("Send /start first to set up your profile.")
            return
        course = session.query(Course).filter_by(id=course_id).first()
        if not course:
            await query.edit_message_text("Couldn't find that course.")
            return

        completed_lesson_ids = {
            lp.lesson_id for lp in
            session.query(LessonProgress).filter_by(user_id=user.id).all()
        }

        rows = []
        for lesson in course.lessons:
            mark = "✅" if lesson.id in completed_lesson_ids else "⬜"
            rows.append([InlineKeyboardButton(f"{mark} {lesson.title}", callback_data=f"acad:lesson:{lesson.id}")])
        rows.append([InlineKeyboardButton("⬅️ All Courses", callback_data="acad:home")])

        text = f"📖 *{md(course.title)}*\n\n{md(course.description)}"
        await query.edit_message_text(text, parse_mode="Markdown", reply_markup=InlineKeyboardMarkup(rows))
    finally:
        session.close()


async def show_lesson(update: Update, context: ContextTypes.DEFAULT_TYPE, lesson_id: int):
    query = update.callback_query
    await query.answer()

    session = SessionLocal()
    try:
        lesson = session.query(Lesson).filter_by(id=lesson_id).first()
        if not lesson:
            await query.edit_message_text("Couldn't find that lesson.")
            return

        if not lesson.content_text:
            if _client is None:
                await query.edit_message_text("⚠️ AI isn't configured — ANTHROPIC_API_KEY is missing.")
                return
            await query.edit_message_text(f"⏳ Preparing \"{lesson.title}\" for the first time...")
            ok = await _generate_lesson(session, lesson)
            if not ok:
                await query.edit_message_text(
                    "⚠️ Couldn't generate this lesson right now. Please try again shortly.",
                    reply_markup=keyboards.back_to_menu_keyboard(),
                )
                return

        rows = [
            [InlineKeyboardButton("📝 Take the quiz", callback_data=f"acad:quizstart:{lesson.id}")],
            [InlineKeyboardButton("⬅️ Back to Course", callback_data=f"acad:course:{lesson.course_id}")],
        ]
        await query.edit_message_text(
            f"📖 *{md(lesson.title)}*\n\n{md(lesson.content_text)}",
            parse_mode="Markdown", reply_markup=InlineKeyboardMarkup(rows),
        )
    finally:
        session.close()


async def _generate_lesson(session, lesson: Lesson) -> bool:
    """Generates + caches lesson content and quiz. Returns False (and
    leaves the lesson uncached) on any failure, so the next open retries
    cleanly rather than caching something broken."""
    course = lesson.course
    prompt = (
        f"Course: {course.title} (category: {course.category.value})\n"
        f"Lesson: {lesson.title}\n"
        f"Brief: {lesson.brief}"
    )
    for attempt in range(2):  # one retry if JSON parsing fails
        try:
            response = _client.messages.create(
                model=config.CLAUDE_MODEL, max_tokens=1400,
                system=config.ACADEMY_LESSON_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}],
            )
            raw = "".join(b.text for b in response.content if b.type == "text").strip()
            data = _parse_lesson_json(raw)
            if data and _validate_lesson_json(data):
                lesson.content_text = data["content"]
                lesson.quiz_json = json.dumps(data["quiz"])
                lesson.generated_at = datetime.utcnow()
                session.commit()
                return True
        except APIError:
            pass
    return False


def _parse_lesson_json(raw: str):
    cleaned = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw.strip(), flags=re.MULTILINE).strip()
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        return None


def _validate_lesson_json(data: dict) -> bool:
    if not isinstance(data, dict) or "content" not in data or "quiz" not in data:
        return False
    if not isinstance(data["content"], str) or len(data["content"]) < 50:
        return False
    quiz = data["quiz"]
    if not isinstance(quiz, list) or len(quiz) == 0:
        return False
    for q in quiz:
        if not all(k in q for k in ("question", "options", "correct_index")):
            return False
        if not isinstance(q["options"], list) or len(q["options"]) < 2:
            return False
        if not isinstance(q["correct_index"], int) or not (0 <= q["correct_index"] < len(q["options"])):
            return False
    return True


# ---------- Quiz flow ----------

async def start_quiz(update: Update, context: ContextTypes.DEFAULT_TYPE, lesson_id: int):
    query = update.callback_query
    await query.answer()

    session = SessionLocal()
    try:
        lesson = session.query(Lesson).filter_by(id=lesson_id).first()
        if not lesson or not lesson.quiz_json:
            await query.edit_message_text("Quiz not available for this lesson yet — open the lesson first.")
            return

        questions = json.loads(lesson.quiz_json)
        context.user_data["academy_quiz"] = {
            "lesson_id": lesson_id, "course_id": lesson.course_id,
            "questions": questions, "index": 0, "correct": 0,
        }
        await _send_question(query, context)
    finally:
        session.close()


async def _send_question(query, context):
    quiz = context.user_data["academy_quiz"]
    q = quiz["questions"][quiz["index"]]
    total = len(quiz["questions"])
    rows = [
        [InlineKeyboardButton(opt, callback_data=f"acad:quizans:{i}")]
        for i, opt in enumerate(q["options"])
    ]
    await query.edit_message_text(
        f"❓ Question {quiz['index'] + 1}/{total}\n\n{q['question']}",
        reply_markup=InlineKeyboardMarkup(rows),
    )


async def answer_quiz(update: Update, context: ContextTypes.DEFAULT_TYPE, selected_index: int):
    query = update.callback_query
    quiz = context.user_data.get("academy_quiz")
    if not quiz:
        await query.answer()
        await query.edit_message_text("This quiz session expired — open the lesson again to retake it.")
        return

    q = quiz["questions"][quiz["index"]]
    correct = selected_index == q["correct_index"]
    if correct:
        quiz["correct"] += 1
        await query.answer("✅ Correct!")
    else:
        correct_text = q["options"][q["correct_index"]]
        await query.answer(f"❌ Not quite — correct answer: {correct_text}", show_alert=True)

    quiz["index"] += 1
    if quiz["index"] < len(quiz["questions"]):
        await _send_question(query, context)
        return

    # Quiz complete
    score, total = quiz["correct"], len(quiz["questions"])
    lesson_id, course_id = quiz["lesson_id"], quiz["course_id"]
    context.user_data.pop("academy_quiz", None)

    session = SessionLocal()
    try:
        user = session.query(User).filter_by(telegram_id=update.effective_user.id).first()
        if not user:
            await query.edit_message_text("Send /start first to set up your profile.")
            return
        existing = session.query(LessonProgress).filter_by(user_id=user.id, lesson_id=lesson_id).first()
        if existing:
            existing.quiz_score, existing.quiz_total = score, total
            existing.completed_at = datetime.utcnow()
        else:
            session.add(LessonProgress(user_id=user.id, lesson_id=lesson_id, quiz_score=score, quiz_total=total))
        session.commit()

        course = session.query(Course).filter_by(id=course_id).first()
        total_lessons = len(course.lessons)
        completed_lessons = (
            session.query(LessonProgress)
            .join(Lesson, LessonProgress.lesson_id == Lesson.id)
            .filter(LessonProgress.user_id == user.id, Lesson.course_id == course_id)
            .count()
        )
        course_complete = completed_lessons >= total_lessons

        text = f"🏁 Quiz complete: {score}/{total} correct.\n\n"
        rows = [[InlineKeyboardButton("⬅️ Back to Course", callback_data=f"acad:course:{course_id}")]]
        if course_complete:
            text += f"🎉 You've completed *{md(course.title)}*!"
            rows.insert(0, [InlineKeyboardButton("🎓 Get Certificate", callback_data=f"acad:cert:{course_id}")])
        await query.edit_message_text(text, parse_mode="Markdown", reply_markup=InlineKeyboardMarkup(rows))
    finally:
        session.close()


# ---------- Certificates ----------

async def request_certificate(update: Update, context: ContextTypes.DEFAULT_TYPE, course_id: int):
    query = update.callback_query
    session = SessionLocal()
    try:
        user = session.query(User).filter_by(telegram_id=update.effective_user.id).first()
        if not user or not await require_premium(update, user):
            return

        course = session.query(Course).filter_by(id=course_id).first()
        total_lessons = len(course.lessons)
        completed_lessons = (
            session.query(LessonProgress)
            .join(Lesson, LessonProgress.lesson_id == Lesson.id)
            .filter(LessonProgress.user_id == user.id, Lesson.course_id == course_id)
            .count()
        )
        if completed_lessons < total_lessons:
            await query.answer()
            await query.edit_message_text(f"Complete all lessons in {course.title} first.")
            return

        existing = session.query(Certificate).filter_by(user_id=user.id, course_id=course_id).first()
        if not existing:
            existing = Certificate(
                user_id=user.id, course_id=course_id,
                certificate_code=f"AFO-{secrets.token_hex(4).upper()}",
            )
            session.add(existing)
            session.commit()
            session.refresh(existing)

        await query.answer()
        png_bytes = generate_certificate_png(user.display_name(), course.title, existing.certificate_code, existing.issued_at)
        await context.bot.send_photo(
            chat_id=update.effective_chat.id,
            photo=InputFile(png_bytes, filename=f"certificate_{course.slug}.png"),
            caption=f"🎓 Certificate of Completion — {course.title}\nID: {existing.certificate_code}",
        )
    finally:
        session.close()


async def list_certificates(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    session = SessionLocal()
    try:
        user = session.query(User).filter_by(telegram_id=update.effective_user.id).first()
        if not user or not await require_premium(update, user):
            return

        certs = session.query(Certificate).filter_by(user_id=user.id).order_by(Certificate.issued_at.desc()).all()
        if not certs:
            text = "No certificates yet — complete a course's lessons, then tap 🎓 Get Certificate."
            if query:
                await query.answer()
                await query.edit_message_text(text, reply_markup=keyboards.back_to_menu_keyboard())
            else:
                await update.message.reply_text(text)
            return

        rows = [
            [InlineKeyboardButton(f"🎓 {c.course.title} ({c.issued_at.strftime('%d %b %Y')})", callback_data=f"acad:cert:{c.course_id}")]
            for c in certs
        ]
        rows.append([InlineKeyboardButton("⬅️ Back", callback_data="acad:home")])
        text = "🎓 Your certificates (tap to resend the image):"
        if query:
            await query.answer()
            await query.edit_message_text(text, reply_markup=InlineKeyboardMarkup(rows))
        else:
            await update.message.reply_text(text, reply_markup=InlineKeyboardMarkup(rows))
    finally:
        session.close()


# ---------- Router ----------

async def academy_router(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    parts = query.data.split(":")
    action = parts[1]

    if action == "home":
        await show_academy_home(update, context)
    elif action == "course":
        await show_course(update, context, int(parts[2]))
    elif action == "lesson":
        await show_lesson(update, context, int(parts[2]))
    elif action == "quizstart":
        await start_quiz(update, context, int(parts[2]))
    elif action == "quizans":
        await answer_quiz(update, context, int(parts[2]))
    elif action == "cert":
        await request_certificate(update, context, int(parts[2]))
    elif action == "certs":
        await list_certificates(update, context)
    else:
        await query.answer()
